<?php

/* 
**  ==========
**  PlaatScrum
**  ==========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2016 PlaatSoft
*/

/*
** ---------------------------------------------------------------- 
** VARIABLE CONFIG ITEMS
** ---------------------------------------------------------------- 
*/

define('DEBUG', 0);
define('MYSQL', 1);

/* Database Localhost Server */
$config['dbuser']			 		= "plaatscrum";
$config['dbpass']			 		= "plaatscrum";
$config['dbname']			 		= "plaatscrum";
$config['dbhost']					= "127.0.0.1";
$config['content_url']	 	 	= "";

/* Server version */
$config['applName']		 	 	= 'PlaatScrum';
$config['applVersion']	 	 	= 'v1.1 (Build 01-01-2016)';
$config['from_email']    	 	= 'info@plaatsoft.nl'; 
$config['base_url'] 		 		= 'http://scrum.plaatsoft.nl';
$config['backup_period']    	 = 30;

/*
** ---------------------------------------------------------------- 
** THE END
** ----------------------------------------------------------------
*/

?>
